import ExcelJS from 'exceljs'

export interface ReportItem {
  id: number
  number: string
  name: string
  description: string
  condition?: string
  sku?: string
  qtyIn: number
  qtyOut: number
  balanceQty: number
  unitPrice: number
  totalPrice: number
  threshold: number
  status: string
}

export interface ReportSummary {
  totalItems: number
  totalValue: number
  lowStockItems: number
}

export interface ReportData {
  title: string
  generatedAt: string
  items: ReportItem[]
  summary: ReportSummary
}

// PDF Generation
export function generatePDFReport(reportData: ReportData): Buffer {
  try {
    // Create a simple text-based report for now
    const reportText = `
${reportData.title}
Generated: ${new Date().toLocaleDateString()}

SUMMARY:
Total Items: ${reportData.summary.totalItems}
Total Value: ${reportData.summary.totalValue.toLocaleString()} RWF
Low Stock Items: ${reportData.summary.lowStockItems}

ITEMS:
${reportData.items.map((item, index) => `
${index + 1}. ${item.name}
   Number: ${item.number}
   Description: ${item.description}
   Condition: ${item.condition || 'N/A'}
   SKU: ${item.sku || 'N/A'}
   Qty In: ${item.qtyIn}
   Qty Out: ${item.qtyOut}
   Balance: ${item.balanceQty}
   Unit Price: ${item.unitPrice.toLocaleString()} RWF
   Total Price: ${item.totalPrice.toLocaleString()} RWF
   Threshold: ${item.threshold}
   Status: ${item.status}
`).join('')}

Report generated by StoreMIS
    `.trim()
    
    return Buffer.from(reportText, 'utf-8')
  } catch (error) {
    console.error('Error generating PDF:', error)
    throw new Error('Failed to generate PDF report')
  }
}

// Excel Generation
export async function generateExcelReport(reportData: ReportData): Promise<Buffer> {
  try {
    const workbook = new ExcelJS.Workbook()
    const worksheet = workbook.addWorksheet(reportData.title)
    
    // Add summary
    worksheet.addRow(['SUMMARY'])
    worksheet.addRow(['Total Items:', reportData.summary.totalItems])
    worksheet.addRow(['Total Value:', `${reportData.summary.totalValue.toLocaleString()} RWF`])
    worksheet.addRow(['Low Stock Items:', reportData.summary.lowStockItems])
    worksheet.addRow([]) // Empty row
    
    // Add headers
    worksheet.addRow(['Number', 'Name', 'Description', 'Condition', 'SKU', 'Qty In', 'Qty Out', 'Balance Qty', 'Unit Price', 'Total Price', 'Threshold', 'Status'])
    
    // Add data rows
    reportData.items.forEach(item => {
      worksheet.addRow([
        item.number,
        item.name,
        item.description,
        item.condition || '-',
        item.sku || '-',
        item.qtyIn,
        item.qtyOut,
        item.balanceQty,
        item.unitPrice,
        item.totalPrice,
        item.threshold,
        item.status
      ])
    })
    
    // Generate buffer
    const buffer = await workbook.xlsx.writeBuffer()
    return Buffer.from(buffer)
  } catch (error) {
    console.error('Error generating Excel:', error)
    throw new Error('Failed to generate Excel report')
  }
}

// CSV Generation
export function generateCSVReport(reportData: ReportData): string {
  try {
    const headers = [
      'Number', 'Name', 'Description', 'Condition', 'SKU', 
      'Qty In', 'Qty Out', 'Balance Qty', 'Unit Price', 
      'Total Price', 'Threshold', 'Status'
    ]
    
    const csvRows = [headers.join(',')]
    
    reportData.items.forEach(item => {
      const row = [
        `"${item.number}"`,
        `"${item.name}"`,
        `"${item.description}"`,
        `"${item.condition || '-'}"`,
        `"${item.sku || '-'}"`,
        item.qtyIn,
        item.qtyOut,
        item.balanceQty,
        item.unitPrice,
        item.totalPrice,
        item.threshold,
        `"${item.status}"`
      ]
      csvRows.push(row.join(','))
    })
    
    return csvRows.join('\n')
  } catch (error) {
    console.error('Error generating CSV:', error)
    throw new Error('Failed to generate CSV report')
  }
}
